spring:
  profiles:
    include:
      - db
      - jwt
      - jasypt
      - image

logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
